#include "MKL25Z4.h"
#include "led.h"

void initLED(){
	SIM_SCGC5 |= SIM_SCGC5_PORTA_MASK;
	SIM_SCGC5 |= SIM_SCGC5_PORTE_MASK;
	
	PORTA->PCR[GREEN_LED_1] &= ~PORT_PCR_MUX_MASK;
	PORTA->PCR[GREEN_LED_2] &= ~PORT_PCR_MUX_MASK;
	PORTA->PCR[GREEN_LED_4] &= ~PORT_PCR_MUX_MASK;
	PORTA->PCR[GREEN_LED_5] &= ~PORT_PCR_MUX_MASK;
	
	PORTA->PCR[GREEN_LED_1] |= PORT_PCR_MUX(1);
	PORTA->PCR[GREEN_LED_2] |= PORT_PCR_MUX(1);
	PORTA->PCR[GREEN_LED_4] |= PORT_PCR_MUX(1);
	PORTA->PCR[GREEN_LED_5] |= PORT_PCR_MUX(1);
	
	PTA->PDDR |= (MASK(GREEN_LED_1) | MASK(GREEN_LED_2) | MASK(GREEN_LED_4) | MASK(GREEN_LED_5));
	PTA->PDOR &= ~(MASK(GREEN_LED_1) | MASK(GREEN_LED_2) | MASK(GREEN_LED_4) | MASK(GREEN_LED_5));
	PTA->PDOR |= MASK(GREEN_LED_1);
	
	PORTE->PCR[RED_LED] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[RED_LED] |= PORT_PCR_MUX(1);
	PTE->PDDR |= MASK(RED_LED);
	PTE->PDOR &= ~MASK(RED_LED);
	PTE->PDOR |= MASK(RED_LED);
}
